### ISSUE TITLE
unable to import FrameRate

### ISSUE THREAD

**Issue by RaminMT** [Viglino/ol-games#10]
Hi,
Thanks for your nice libraries, ol-ext & ol-games
I want to use itin a VueJS application, I installed the package from npm but I can't import the FrameRate to use with Sprite

**Comment by Viglino** [comment]
It seems the file was not committed...
I'll try to push a new version asap...

**Comment by RaminMT** [comment]
Alright, thanks man
I just grabbed the definition from `dist/ol-games.js` and changed like this:
```
import ol_ext_inherits from 'ol-ext/util/ext'
import ol_Observable from 'ol/Observable'
import ol_Control from 'ol/control/Control'
import ol_ext_element from 'ol-ext/util/element'

var ol_control_FrameRate = function(opt_options) {
  var options = opt_options || {};
  var element = ol_ext_element.create('DIV', {
    className: (options.className || "ol-framerate") + (options.target ?  '':' ol-unselectable ol-control')
  });
  var canvas = this.canvas_ = document.createElement('canvas');
  canvas.width = 100;
  canvas.height = 40;
  element.appendChild(canvas);
  this.ctx = canvas.getContext('2d');
  this.ctx.font = "bold 11px sans-serif";
  this.ctx.textAlign = "center";
  this.ctx.textBaseline = "top";
  this.ctx.fillStyle = "#fff";
  this.ctx.fillRect(1, 15, 99,45);
  ol_Control.call(this, {
    element: element,
    target: options.target
  });
};
ol_ext_inherits (ol_control_FrameRate, ol_Control);

ol_control_FrameRate.prototype.setMap = function (map) {
  if (this._listener) ol_Observable.unByKey(this._listener);
  this._listener = null;
  ol_Control.prototype.setMap.call(this, map);
  if (this.getMap()) {
    this._listener = this.getMap().on("precompose", this.update_.bind(this));
    this.time_ = (new Date()).getTime();
  }
};
ol_control_FrameRate.prototype.update_ = function (e) {
  var dt = e.frameState.time - this.time;
  this.time = e.frameState.time;
  // Move image left
  this.ctx.drawImage(this.canvas_, 1, 15, 99,this.canvas_.height, 0,15,99,this.canvas_.height );
  // Draw text
  var fps = Math.round(500/dt);
  this.ctx.clearRect(0,0,100,15);
  this.ctx.fillStyle = "#000";
  this.ctx.fillText((2*fps)+" fps",50,0);
  this.ctx.strokeStyle = "#fff";
  this.ctx.beginPath();
  this.ctx.moveTo(100, 15);
  this.ctx.lineTo(100, 40);
  this.ctx.closePath();
  this.ctx.stroke();
  this.ctx.strokeStyle = (fps>20 ? "#060" : fps>12 ? "#f80" : "#800" );
  this.ctx.beginPath();
  this.ctx.moveTo(100, 40 - fps/2);
  this.ctx.lineTo(100, 40);
  this.ctx.closePath();
  this.ctx.stroke();
};

export default ol_control_FrameRate
```
Then imported this my project, I'm yet achieved my goal, Do I did this correct?

**Comment by Viglino** [comment]
I've pushed a new version and published on npm ol-games@1.0.4

**Comment by RaminMT** [comment]
Hi again,
been away for a while

Thank you friend

**Comment by RaminMT** [comment]
I got questions,
What does frame rate do exactly?
How should I use the states? What's the definition of line & length?
Currently I have this: 
```
let sprite = new Sprite({
        position: [0, 0],
        src: require('@/assets/images/markers/arrow.svg'),
        size: 100,
        frameRate: 1,
        states: {	idle: { line: 0, length: 1 } }
      })
```
Is this alright? changing framerate do nothing and changing line or length causes blinking of the sprite

**Comment by Viglino** [comment]
Sprites are animated using [Sprite sheets:](https://www.google.com/search?q=sprite+sheet)
<img src="https://viglino.github.io/ol-games/examples/data/robin.png" width="250"></img>
ie: a set of square images that animate the Sprite.
The size of each image in the sprite sheet depends on the size options (default 64).
Each lines on the sprite sheet defines a state with a number of images that animates the state.
The default states are those proposed by [the Universal-LPC-spritesheet project](https://github.com/jrconway3/Universal-LPC-spritesheet):
> Robin is walking left on line 9 and is animating thought step 1 to 9
> The `walk_W` state is defined as: { line: 9, start:1, length: 8 } of the sprite image
The frame rate is the rate for animation updates (in ms), default is 100 ms (10 images/s)

You can define your own states: 
`        states: {	idle: { line: 0, length: 1 } }`
This means there is no animation on idle (`length: 1` = only one image, `line: 0` = first line of the sprite sheet).

Look at [this example](https://viglino.github.io/ol-games/examples/map.sprite.html) to see the states in action.
You can change the state of a Sprite using `changeState()` method and listen to the `state`.
Use `update()` the sprite in the game loop.

-----

Using a more simple sprite sheet:
<img src="https://viglino.github.io/ol-games/examples/data/plane.png" width="250"></img>
The code for the sprite is:
```javscript
var plane = new ol.Sprite({
  position: [250000, 6250762],
  src: "data/plane.png",
  size: 175,
  scale: 0.4,
  frameRate: 10,
  // Define the states for the plane
  states: {
    idle: { line:0, length:3 } 
  }
}); 
```
This means that the idle state has 3 steps (on first line) and will update every 10ms that makes the plane propeller rotate...
