### ISSUE TITLE
 ol.Sprite.move() make misstakes when the direction is due east/ west/south

### ISSUE THREAD

**Issue by PongChen** [Viglino/ol-games#12]
https://viglino.github.io/ol-games/examples/map.sprite.path.html

replace the path with 
// 向上
  var path2 = new ol.geom.LineString([
  [265500, 6270000],[265500, 6280000],[265500, 6285000],[265500, 6290000],[265500, 6295000],[265500, 6300000],

  ]);
  // 向下
  var path = new ol.geom.LineString([
  [265500, 6300000],[265500, 6295000],[265500, 6290000],[265500, 6285000],[265500, 6280000],[265500, 6270000],

  ]);
as you can see theirs difference

**Comment by Viglino** [comment]
I fix the issue when path has vertical or horizontal segments.

**Comment by PongChen** [comment]
> I fix the issue in the last commit when path has vertical or horizontal segments.

Awesome！
little does one think  you  solve it so soon ，have a good day thanks

**Comment by Viglino** [comment]
Most difficult is to find the bugs...
