### ISSUE TITLE
HexMap error

### ISSUE THREAD

**Issue by sl0burn** [Viglino/ol-games#17]
```ol_source_ImageCanvas.call (this, { canvasFunction: this.drawHex });```

On above line (line 29 of HexMap.js) i am getting 
 ```Uncaught TypeError: Class constructor ImageCanvasSource cannot be invoked without new```

When constructing the hex map per below
```
const hexgrid = new HexGrid ({ size:4000 });
const hexmap = new HexMap({ hexGrid: hexgrid });
```

I saw in ol-ext that you had to make some changes for ol 7 so maybe similar problems here ?

**Comment by sl0burn** [comment]
I see now that the code has already been updated from what I am running through NPM. (1.0.4)

**Comment by Viglino** [comment]
Yes, it's a new [issue with ol v7](https://github.com/Viglino/ol-ext/issues/839).
I'll publish a new version asap.

**Comment by Viglino** [comment]
ol-games v2.0.0 is out! https://www.npmjs.com/package/ol-games

**Comment by sl0burn** [comment]
Looks good now, thanks.
