### ISSUE TITLE
Example map.gameloop dont work?

### ISSUE THREAD

**Issue by DebuggerAK** [Viglino/ol-games#5]
https://viglino.github.io/ol-games/examples/map.gameloop.html

Mixed Content: The page at 'https://viglino.github.io/ol-games/examples/map.gameloop.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://viglino.github.io/ol-ext/dist/ol-ext.css'. This request has been blocked; the content must be served over HTTPS.

Uncaught TypeError: ol.inherits is not a function
    at ol-games.js:41
map.gameloop.html:100 Uncaught TypeError: ol.Game is not a constructor
    at map.gameloop.html:100

:(

**Comment by Viglino** [comment]
Yes the script must be called using https...
I've changed the link to solve the bug :worried: 
The examples should be running fine now :smile:

**Comment by DebuggerAK** [comment]
Thank you! This feature is very nice!
