### ISSUE TITLE
How to draw a tail while a plane is flying?

### ISSUE THREAD

**Issue by asimus90** [Viglino/ol-games#7]
Hey, i use ol-games lib and i set a path for animation. But i want to add a tail/trace to see where i've left on the path/animation.
Is it possible to add extra linestring dynamically to follow plane while animating?

From showcase: [plane is flying on the path!](https://viglino.github.io/ol-games/examples/map.sprite.path.html)

Thanks!

**Comment by Viglino** [comment]
You can get information on the current point on the path the plane is going to using `plane.destination`.
Then you can create a LineString using the points of the path and the current position...
See #6 for more information.
@+
