### ISSUE TITLE
OL 6

### ISSUE THREAD

**Issue by sign0** [Viglino/ol-games#8]
Hi,

We have identified a problem to update OL6 with ol-ext and ol-games.
When installing packages, we get the following error message:

> WARNING in ./node_modules/ol-games/source/HexMap.js 31:0-11
> export 'inherits' (imported as 'ol_inherits') was not found in 'ol'

Do you know how we can solve this problem ?

Thanks,
Adrien

**Comment by Viglino** [comment]
ol-games is not fully compatible with ol6.
Modules are not includes correctly...
```javascript
import {inherits as ol_inherits} from 'ol'
....
ol_inherits (ol_source_HexMap, ol_source_ImageCanvas);
```
should be:
```javascript
import ol_ext_inherits from 'ol-ext/util/ext'
...
ol_ext_inherits (ol_source_HexMap, ol_source_ImageCanvas);
```
As ol6 doesn't expose the method anymore...

I'll try to see what can be done asap...

NB: ol-games has not been tested as modules... tell me if you have other issues like that...

**Comment by sign0** [comment]
```javascript
import ol_ext_inherits from 'ol-ext/util/ext'
...
ol_ext_inherits (ol_source_HexMap, ol_source_ImageCanvas);
```

This solve the problem with the redblobgames hexagonal layer.
Thanks 👍
