### ISSUE TITLE
HexMap rotation

### ISSUE THREAD

**Issue by sign0** [Viglino/ol-games#9]
I am trying to rotate the entire hexagonal grid (canvas of HexMap)...

Unfortunately I haven't found a documented method of doing this through ol-ext and ol-games.
Do you have any idea if this might be possible with a herited method somewhere or with an other solution ?

**Comment by Viglino** [comment]
Hexgrid is a coordinate system whose axes are defined from the original map projection (see https://viglino.github.io/ol-games/examples/map.hexmap.html with axial, offset or cube).
You can try to change the source projection to introduce a rotation to the projection but it is quite tricky...
